In [2]:
import numpy as np

In [68]:
v1=np.array([2, 3])
v2=np.array([4, 6])
v4=np.array([4, 8, 7])
c1, c2=4, 1
print(c1*v1+c2*v2)
v3=np.array([[3, 1, 4],
            [1,  2, 5]])

[12 18]


In [27]:
np.linalg.solve(v3, [7, 4])

array([2., 1.])

In [42]:
A=np.column_stack(( v2, v4, v1))
np.linalg.solve(A, [7, 4, 5])

array([ 1.5, -2.5,  5.5])

In [46]:
A=np.column_stack((v1, v2, v4))

In [38]:
v1=np.array([2, 3])
v2=np.array([4, 5])
A=np.column_stack((v1, v2))
np.linalg.solve(A, [7, 4])

array([-9.5,  6.5])

In [49]:
np.linalg.matrix_rank(arr)

np.int64(2)

In [59]:
arr=np.arange(1, 10).reshape(3, 3)

In [60]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.linalg.matrix_rank(arr1)

np.int64(3)

In [17]:
arr1=np.array([[2, 5, 6],
       [9, 7, 6],
       [2, 4, 6]])

In [11]:
v1=np.array([2, 4])
v2=np.array([1, 2])
v3=np.array([0, 5])
A=np.column_stack([v1, v2])
b=np.array([3, 6])
c, resid, rank, _=np.linalg.lstsq(A, b, rcond=None)
xato=np.linalg.norm(A@c-b)
print(f'{xato:.17f}')

0.00000000000000298


In [16]:
np.linalg.matrix_rank([v2, v3])

np.int64(2)

In [100]:
np.dot(A, c)

array([7., 4.])