In [1]:
import numpy as np

In [8]:
D=np.diag([4, 0.5])
print(D)

[[4.  0. ]
 [0.  0.5]]


In [9]:
V=np.array([2, 6])
print(D@V)

[8. 3.]


In [10]:
I=np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
A=np.array([[5, 2, 1],
           [0, 3, 4],
           [1, 1, 2]])
print(np.allclose(A@I, A))

True


In [23]:
I=np.eye(2)
I2=np.eye(4)


In [13]:
mat=np.array([[1, 2],
              [2, 3]])


In [14]:
np.allclose(I@mat, mat)

True

In [26]:
np.allclose(mat@I, mat)

True

In [18]:
I=2*I

In [19]:
I@mat

array([[2., 4.],
       [4., 6.]])

In [25]:
mat@I

array([[1., 2.],
       [2., 3.]])

In [30]:
A=np.array([[3, 2], 
            [4, 3]])
print(np.linalg.det(A))

1.0


In [31]:
A_inv=np.linalg.inv(A)

In [32]:
print(np.round(A@A_inv))

[[1. 0.]
 [0. 1.]]


In [51]:
A=np.array([[3, 2], 
            [1, 4]])
B=np.array([[2, 6], 
            [1, 3]])

detA=4*3-1*2=10
detB=3*2-1*6=0
A teskarilanadi B teskarilanmaydi

In [38]:
A_inv=np.linalg.inv(A)
print(A_inv)
I=np.eye(2)

[[ 0.4 -0.2]
 [-0.1  0.3]]


In [ ]:
print(np.linalg.inv(B))


LinAlgError: Singular matrix

In [39]:
print(np.allclose(A@A_inv, I))

True


In [42]:
np.linalg.matrix_rank(B)

np.int64(1)

In [61]:
def Inv_boladimi(x):
    rows, columns=x.shape
    if rows!=columns:
        print('Bu kvadrat funksiya emas')
    elif np.linalg.det(x)==0:
        print('Bu matritsa determinanti 0 ga teng')
    else:
        return np.linalg.inv(x)
        

In [62]:
K=Inv_boladimi(A)
print(np.allclose(K@A, I))

True


In [63]:
K

array([[ 0.4, -0.2],
       [-0.1,  0.3]])