In [1]:
import numpy as np

In [2]:
A=np.eye(3)

In [12]:
B=np.array([[1, 3, 2],
            [5, 4, 3],
            [6, 7, 5]])

In [14]:
S=np.linalg.pinv(B)
np.round(S)

array([[-0.,  0., -0.],
       [ 0., -0.,  0.],
       [ 0., -0.,  0.]])

In [11]:
np.round(A@S)

array([[  0.,  -1.,   1.],
       [  3.,  -9.,   7.],
       [ -4.,  14., -11.]])

In [7]:
np.linalg.matrix_rank(B)

np.int64(3)

In [ ]:
v=np.array([[2, 0],
            [0, 5]])
v1=np.array([[1, 0],
            [0, 1]])
v2=np.array([[3, 6],
            [1, 2]])

In [23]:
v[0, 0]*v[1, 1]-v[0, 1]*v[1, 0]

np.int64(10)

In [24]:
v1[0, 0]*v1[1, 1]-v1[0, 1]*v1[1, 0]

np.int64(1)

In [25]:
v2[0, 0]*v2[1, 1]-v2[0, 1]*v2[1, 0]

np.int64(3)

In [77]:
A=np.array([[5, 3, 4, 5], [2, 8, 9, 6], [1, 4, 7, 8], [2, 6, 5, 8]])
v=np.array([1, -1, 2, 4])
E=A@v
print(E)

[30 36 43 38]


In [78]:
E/v

array([ 30. , -36. ,  21.5,   9.5])

In [70]:
E==2*v

array([False, False, False])

In [30]:
v=np.array([4, 2])

In [31]:
E2=A@v

In [33]:
E2/v

array([5., 5.])

In [34]:
A@v==5*v

array([ True,  True])

In [79]:
vals, vecs=np.linalg.eig(A)

In [82]:
print(np.round(vals))
print(np.round(vecs))

[21.+0.j  4.+0.j  1.+2.j  1.-2.j]
[[ 0.+0.j -1.+0.j -0.-0.j -0.+0.j]
 [ 1.+0.j  0.+0.j -1.+0.j -1.-0.j]
 [ 0.+0.j  0.+0.j  0.-0.j  0.+0.j]
 [ 1.+0.j -0.+0.j  0.+0.j  0.-0.j]]


In [74]:
v=vecs[:, 0]

In [75]:
np.allclose(A@v, vals[0]*v)

True

In [62]:
vals[0]*v

array([-2.0524452 , -2.99128927])

In [63]:
A@v

array([-5.30253185, -7.72805365])

In [67]:
D=np.diag([5, 3, 5])
vals, vecs=np.linalg.eig(D)
print(vals)
print(vecs)

[5. 3. 5.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [83]:
N=np.array([[3, 6], [1, 2]])

In [85]:
vals, vecs=np.linalg.eig(N)

In [86]:
print(vals)
print(vecs)

[5. 0.]
[[ 0.9486833  -0.89442719]
 [ 0.31622777  0.4472136 ]]


In [87]:
np.linalg.det(N)

np.float64(0.0)

In [88]:
a=np.array([[1, 9], [8, 7]])

In [89]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-5., 13.]), eigenvectors=array([[-0.83205029, -0.6       ],
       [ 0.5547002 , -0.8       ]]))